### ISSUE TITLE
Here we are - distributed computing in Kind!

### ISSUE THREAD

**Issue by dumblob** [litereum/litereum#1]
Wow, this did took much less than expected from the conclusions in https://github.com/uwu-tech/Kind/issues/167 :wink:.

But yeah, I understand that this is quite a special case.

**Comment by VictorTaelin** [comment]
This isn't exactly a distributed computation thing. Litereum can be seen as a very slow, but decentralized, interpreter of a low-order subset of Kind featuring only datatypes, global recursive functions and a few Uint64 primitives. It is essentially a minimal, functional Ethereum.

People can upload types and functions to the network, just like people can deploy smart-contracts to Ethereum. Users can interact with uploaded functions by calling them. These functions can alter the global state - which is just a list of types and functions - to emulate DApps. So, for example, a `MyCoin` function could alter a global `MyCoin.Balances : Map<U64>` map of user balances to implement a currency. External accounts can be emulated by implementing functions that only you control, based on your favorite signature schemes.

**Comment by VictorTaelin** [comment]
This is just an early WIP, though - you shouldn't be here :)

We plan to make the initial announcement around Oct 31.

**Comment by dumblob** [comment]
> This is just an early WIP, though - you shouldn't be here :)
> 
> We plan to make the initial announcement around Oct 31.

Oh, I'll be silent then. Closing :wink:.
